### ISSUE TITLE
Add missing CRUD to Element Tree

### ISSUE THREAD

**Issue by ThomasJayWilliams** [ThomasJayWilliams/SDML.NET#26]
Need to add all create, read, update and delete operations for tree nodes.

**Comment by ThomasJayWilliams** [comment]
Basically, element tree provides irrational tree structure for element and its string representation. IT can be found at SDML.NET.Renderer.DataStructures.ElementTree. So, at the moment there are no all CRUD operations, so they need to be added. The regular remove, update, read and add operations for tree nodes would be enough.

**Comment by OnesQuared** [comment]
So for this part, this is nothing too crazy and just a simple operations, something like the add functionality. Create would make an empty tree node and if root exist a child node would be made? update would just replace the data and delete would delete, is there a tag or id for the nodes or just do it like add

**Comment by ThomasJayWilliams** [comment]
Hmm, I didn't finish implementing tree. About operations - yeah, nothing crazy, simple operations. About ID - looks like you'll have to add it and delete nodes by ID. I'm not sure if I will have time to review you changes, so I guess I'll review them tomorrow, if you'll finish. But if you'll have any questions - ask here, I'll be checking GitHub from time to time.

**Comment by OnesQuared** [comment]
I tried an attempt at making the crud operations in the issue branch, not too sure about create, but then again not even sure about all the others haha. The main idea was to add an id variable to the element node class and then search using that in update delete and read.

**Comment by ThomasJayWilliams** [comment]
Good job. I'll create some issues for you later. For now - thanks for help.
