### ISSUE TITLE
Rename SDML to Sdml

### ISSUE THREAD

**Issue by ThomasJayWilliams** [ThomasJayWilliams/SDML.NET#28]
Currently, huge amount of classes and files have prefix "SDML". But due to .NET standards they all have to be renamed on "Sdml". All prefixes need to replaced all over the code, including classes, interfaces, members, files and directories. But not projects.

**Comment by ThomasJayWilliams** [comment]
If you have suggestions or questions write them here as a comment.

**Comment by ThomasJayWilliams** [comment]
Oh, and would be nice if you'll add issue you're working on into In Process tab in SDML.NET library project. If you don't permissions tell, I'll see what I can do.

**Comment by OnesQuared** [comment]
For the progress tab in the SDML.NET Library dragged it over, and I assume that is what I should have done.

Also if I am understanding correctly, all the .cs files, class, etc that has SDML should be Sdml, I've made some changes to the SDML.NET/src/SDML.NET in the Issue#28_Rename_SDML_to_Sdml branch. Let me know if what I have made is correct

**Comment by ThomasJayWilliams** [comment]
Everything's good, except projects: don't rename projects, let them be as they are. Also, don't separate changes. This is a bad approach - make commit for every single file. Just collect some changes and then commit them all at once. But keep in mind that huge commits also aren't good. Everything else is good. Keep going.

Oh, and by the way - if you want me to help you with your personal projects I'll be glad to help.

**Comment by ThomasJayWilliams** [comment]
When you will finish just change label to "code review" and make a merge request to master. When you'll do this I will review all code and merge it.

**Comment by OnesQuared** [comment]
I assume you mean by don't separate change is don't make multiple commit to the same file? and I'll make sure do keep the Issue numbers correct, and Change label when I'm done

**Comment by ThomasJayWilliams** [comment]
Thanks. All these rules will help to keep repository clean and understandable.

About commits - I mean that pushing small changes separate commit is a bad idea. If changes you're making are connected to the same issue and basically contain the part of one task better push them as single commit. This will also help keep repository clean. Big amount of small commits creates mess in history and makes it harder to investigate. But it's crucial to keep commits in acceptable size, big commits are also bad.
